<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/PML/Day_28_17_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# from google.colab import drive
# drive.mount('/content/drive')


import numpy as np
import pandas as pd

import os
os.chdir('/content/drive/MyDrive/CDAC/')

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

from numpy import random
from collections import Counter

from numpy.linalg import inv
from numpy.linalg import eig

import matplotlib
from matplotlib import pyplot as plt

import seaborn as sns

import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from scipy.stats import chisquare
from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from scipy.stats import f
from sklearn.metrics import mean_squared_error

from sklearn.metrics import roc_auc_score

#========================================================================

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.discrete.discrete_model import MNLogit

import sklearn
from sklearn.model_selection import train_test_split



import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

from statsmodels.stats.outliers_influence import variance_inflation_factor

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler

# from category_encoders import BinaryEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier


from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.metrics import mean_squared_error
from math import sqrt


import tensorflow

from tensorflow.keras.models import Sequential # helps with the forward and backward propagation
from tensorflow.keras.layers import Dense # this is for the hidden, input and output layers
from tensorflow.keras.layers import ReLU   # activation function
from tensorflow.keras.layers import Dropout   # switching off the neurons

from sklearn.naive_bayes import GaussianNB

# 🔰Naive Bayes🔰



In [6]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'diabetes')
x= df.drop('Outcome', axis=1)  # column of predictors
y= df.Outcome   # column of response

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

gnb = GaussianNB()

mod1 = gnb.fit(x_train,y_train)

y_pred = mod1.predict(x_test)

print(confusion_matrix(y_test,y_pred))

[[106  17]
 [ 15  54]]


In [11]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'iris')

x= df.drop('Species', axis=1)  # column of predictors
y= df.Species   # column of response

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

gnb = GaussianNB()

mod2 = gnb.fit(x_train,y_train)

y_pred = mod2.predict(x_test)

print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0 14  0]
 [ 0  0 13]]
