<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/PML/Day_17_04_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

from numpy import random
from collections import Counter

from numpy.linalg import inv
from numpy.linalg import eig

import matplotlib
from matplotlib import pyplot as plt

import seaborn as sns

import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from scipy.stats import chisquare
from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from scipy.stats import f
from sklearn.metrics import mean_squared_error


#========================================================================

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

import sklearn
from sklearn.model_selection import train_test_split



import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
import os
os.chdir('/content/drive/MyDrive/CDAC/')

In [12]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx' ,sheet_name = 'stackloss')

In [13]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('StackLoss', axis=1),df.StackLoss, test_size=0.1, random_state=20)


In [14]:

# Creating an instance for the function
regr1 = LinearRegression()

array(['AirFlow', 'WaterTemp', 'AcidConc'], dtype=object)

In [15]:
regr1.fit(x_train,y_train)


LinearRegression()

In [16]:
regr1.intercept_


np.float64(-33.281344575611186)

In [17]:
regr1.coef_


array([ 0.70013521,  1.34985785, -0.22974125])

In [21]:
# Number of features
regr1.feature_names_in_

array(['AirFlow', 'WaterTemp', 'AcidConc'], dtype=object)

In [19]:
# R2
regr1.score(x_train,y_train)

0.9080862696530125

In [20]:
#predict
regr1.predict(x_test)

array([10.83134469, 14.08460126, 10.34327252])

In [24]:
from sklearn.preprocessing import StandardScaler
scl = StandardScaler()

x_train = scl.fit_transform(x_train)
x_test = scl.transform(x_test)
regr2 = LinearRegression()
regr2.fit(x_train,y_train)

regr2.intercept_   # intercept
regr2.coef_    # coefficients

array([ 6.19332814,  4.40861726, -0.90286981])

In [35]:
from sklearn.preprocessing import StandardScaler
scl = StandardScaler()
x_train, x_test, y_train, y_test = train_test_split(df.drop('StackLoss', axis=1),df.StackLoss, test_size=0.1, random_state=20)

In [34]:
x_train = scl.fit_transform(x_train)
x_test = scl.transform(x_test)

In [29]:
x_train = pd.DataFrame(x_train,columns=['AirFlow','WaterTemp','AcidConc'])
x_test = pd.DataFrame(x_test,columns=['AirFlow','WaterTemp','AcidConc'])
regr2 = LinearRegression()
regr2.fit(x_train,y_train)

LinearRegression()

In [31]:
regr2.intercept_   # intercept

np.float64(18.666666666666668)

In [32]:
regr2.coef_    # coefficients

array([ 6.19332814,  4.40861726, -0.90286981])

In [33]:
regr2.feature_names_in_

array(['AirFlow', 'WaterTemp', 'AcidConc'], dtype=object)

In [59]:
df = pd.DataFrame({'values' : [3,6,5,1,6,8,3,8,9,4]})


df['StdSale'] = (df.values-np.mean(df.values))/np.std(df.values,ddof=1)

In [61]:
df.head()

,values,StdSale
0,3,-0.890045
1,6,0.270883
2,5,-0.116093
3,1,-1.663997
4,6,0.270883


# 🔰Min Max Scaler🔰

In [78]:
from sklearn.preprocessing import MinMaxScaler
minmax =  MinMaxScaler()

In [64]:
df['MinMax'] = (df.values - min(df.values)) / (max(df.values)- min(df.values))

In [79]:
df = pd.DataFrame({'values' : [3,6,5,1,6,8,3,8,9,4]})


df1_minmax_scaled = minmax.fit_transform(df)

In [81]:
df1_minmax_scaled

array([[0.25 ],
       [0.625],
       [0.5  ],
       [0.   ],
       [0.625],
       [0.875],
       [0.25 ],
       [0.875],
       [1.   ],
       [0.375]])

# 🔰Robust scaler🔰

In [ ]:
from sklearn.preprocessing import RobustScaler

In [85]:
df = pd.DataFrame({'Values' : [3,6,5,1,6,8,3,8,9,4]})
#                                 median ----------------------------       IQR
df['Robust'] = (df.Values-np.median(df.Values))/(np.percentile(df.Values,75)-np.percentile(df.Values,25))

In [86]:
df

,Values,Robust
0,3,-0.588235
1,6,0.117647
2,5,-0.117647
3,1,-1.058824
4,6,0.117647
5,8,0.588235
6,3,-0.588235
7,8,0.588235
8,9,0.823529
9,4,-0.352941


In [90]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'salaries')
df.head()

,rank,discipline,yrs_phd,yrs_service,gender,salary
0,Prof,B,19,18,Male,139750
1,Prof,B,20,16,Male,173200
2,AsstProf,B,4,3,Male,79750
3,Prof,B,45,39,Male,115000
4,Prof,B,40,41,Male,141500


In [92]:
df = df[['yrs_service','gender','salary']]
df.head()

,yrs_service,gender,salary
0,18,Male,139750
1,16,Male,173200
2,3,Male,79750
3,39,Male,115000
4,41,Male,141500


In [93]:
gender_dum = pd.get_dummies(df.gender,drop_first=True).astype(int)
gender_dum.head()

,Male
0,1
1,1
2,1
3,1
4,1


In [94]:
df = pd.concat([df,gender_dum], axis=1)
df = df.drop('gender', axis=1)
df.head()

,yrs_service,salary,Male
0,18,139750,1
1,16,173200,1
2,3,79750,1
3,39,115000,1
4,41,141500,1


In [95]:
# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('salary', axis=1),df.salary, test_size=0.2, random_state=20)

In [96]:
# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

                            OLS Regression Results                            
Dep. Variable:                 salary   R-squared:                       0.121
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     21.52
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           1.75e-09
Time:                        06:41:35   Log-Likelihood:                -3698.4
No. Observations:                 317   AIC:                             7403.
Df Residuals:                     314   BIC:                             7414.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
yrs_service   701.6382    125.946      5.571      

const term equal to 8857 inicates the salary of the person for whom year_service
is equal to zero .\
 and male is equal to zero. which menas gender is female which is nothing but the refernce level.

the starting salry for the males is equal to 88570 + 13680

In [100]:
2.08-1.7*1.223529411764706

0.0

In [ ]:
# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('salary', axis=1),df.salary, test_size=0.2, random_state=20)

# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())