<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/Stats/Day_1_stats_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd

In [45]:
x1 =[4,8,7,6,9]
type(x1)

str(x1)
type(x1)

a1 = np.array(x1)
type(a1)

numpy.ndarray

In [192]:
x2 = [6,9,1,3,2]

#Creating 2D array
a2 = np.array([x1,x2])
a2


[i for i in range(11)]

list(range(11))

a1 = np.arange(11)
a1

a2 = np.arange(8,11)
a2

a3 = np.arange(24,5,-2)
a3

a3 = np.arange(5,25,4)
a3

a3 = np.arange(2,20,2)
a3

a3 = np.arange(10,2,-2)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
np.linspace(10,20,2)

#this cmd givea array including the start and end this command give gap between them
# 3rd values can not be in decimal . bcz we are dividing the numbers in gaps

np.linspace(10,27,6)

np.linspace(10,27, 6, endpoint= False)
# endpoint will be excluded

array([10.        , 12.83333333, 15.66666667, 18.5       , 21.33333333,
       24.16666667])

In [75]:
a1 = np.array([4,8,6,5,9])
a1

np.append(a1,3)

a1 = np.append(a1,3)
a1

a2 = np.array([2,9,8])

a3 = np.concatenate((a1,a2))
a3

a1

array([4, 8, 6, 5, 9, 3])

In [ ]:
## remove, pop, del are cmds used to removing elemts from list.

In [80]:
a1 = np.array([3,6,5,7,8])
a2 = np.insert(a1,3,9)

a1
a2

np.delete(a2,2)

array([3, 6, 9, 7, 8])

In [95]:
a1 = np.array([3, 2, 6, 7, 8, 5, 4, 6])
a1

len(a1)

a2 = a1.reshape(4,2)
a2

# array([[3, 2],   after seeing the no. of square brackets give the count of dimensions of array
#        [6, 7],
#        [8, 5],
#        [4, 6]])


a3 = a1.reshape(2,4)
a3


a4 = a1.reshape(2,2,2)
a4

#==========================================================================

a1 = np.array([3, 2, 6, 7, 8, 5, 4, 6, 1])
a1

len(a1)

a2 = a1.reshape(3,3)
a2


array([[3, 2, 6],
       [7, 8, 5],
       [4, 6, 1]])

In [99]:
a1 = np.array([1,3,5,7,9,2,4,6,8,0])  #-1 will decide teh number of the rows but 1 will decide the number of columns..
a2 = a1.reshape(-1,1)
a2

array([[1],
       [3],
       [5],
       [7],
       [9],
       [2],
       [4],
       [6],
       [8],
       [0]])

In [100]:
a3 = a1.reshape(-1,2) #-1 will decide teh number of the rows but 2 will decide the number of columns..
a3

array([[1, 3],
       [5, 7],
       [9, 2],
       [4, 6],
       [8, 0]])

In [102]:
a4 = a3[2]
a4

a3[2]

array([9, 2])

In [103]:
a3[2,:]

array([9, 2])

In [107]:
# it  will infinte rows but 1st columns
a3[:,1]

a3[1:4,1]

array([7, 2, 6])

In [110]:
a3[[2,4],:] # rows are 2,4 are only rows but columns are infintw

array([[9, 2],
       [8, 0]])

In [112]:
a3[:,[1]]

array([[3],
       [7],
       [2],
       [6],
       [0]])

In [128]:
newcol = np.array([3,1,7,9]) ## it wil reshape the array turn into row to columns
newcol

newcol = newcol.reshape(-1,1)
newcol

array([[3],
       [1],
       [7],
       [9]])

In [170]:
a4 = np.array([1,2,3,4,5,6,7,8])
a4 = a4.reshape(4,2)

a4 = np.hstack([a4, newcol])
a4

array([[1, 2, 3],
       [3, 4, 1],
       [5, 6, 7],
       [7, 8, 9]])

In [171]:
newrow = np.array([1, 2, 3])

a4 = np.vstack([a4, newrow])
a4

array([[1, 2, 3],
       [3, 4, 1],
       [5, 6, 7],
       [7, 8, 9],
       [1, 2, 3]])

In [172]:
a4 = np.insert(a4 , 0 , [11, 12, 13], axis=0)
a4

array([[11, 12, 13],
       [ 1,  2,  3],
       [ 3,  4,  1],
       [ 5,  6,  7],
       [ 7,  8,  9],
       [ 1,  2,  3]])

In [173]:
a4 = np.insert(a4 , 2 , [21, 22, 23, 24, 25, 26], axis=1)
a4

array([[11, 12, 21, 13],
       [ 1,  2, 22,  3],
       [ 3,  4, 23,  1],
       [ 5,  6, 24,  7],
       [ 7,  8, 25,  9],
       [ 1,  2, 26,  3]])

In [189]:
a5 = np.array([0,0,0,0])
a5

a5 = np.vstack([a4,a5])
a5

array([[11, 12, 21, 13],
       [ 1,  2, 22,  3],
       [ 3,  4, 23,  1],
       [ 5,  6, 24,  7],
       [ 7,  8, 25,  9],
       [ 1,  2, 26,  3],
       [ 0,  0,  0,  0]])

In [190]:
a5 = np.delete(a5,0,axis=0)
a5

array([[ 1,  2, 22,  3],
       [ 3,  4, 23,  1],
       [ 5,  6, 24,  7],
       [ 7,  8, 25,  9],
       [ 1,  2, 26,  3],
       [ 0,  0,  0,  0]])

In [191]:
a5 = np.delete(a5 ,(0,2) ,axis=1)
a5

array([[2, 3],
       [4, 1],
       [6, 7],
       [8, 9],
       [2, 3],
       [0, 0]])

In [202]:
a1 = np.arange(1,10).reshape(3,3)
a1

a2= np.array([0,0,0])
a2

a3 = np.vstack([a2,a1])
a3

a4 = np.array([10, 20 , 30 ,40])
a4

a4 = a4.reshape(-1,1)
a4

a5 = np.hstack([a3, a4])
a5

array([[ 0,  0,  0, 10],
       [ 1,  2,  3, 20],
       [ 4,  5,  6, 30],
       [ 7,  8,  9, 40]])

## Broadcasting

In [218]:
# broacasting make it possible that to repeat the same operation across all the values
a1 = np.array([2,3,4,5,6])
a2 = 2*a1 + 5

a1      ## array([2, 3, 4, 5, 6])
a2      ## array([9, 11, 13, 15, 17])
a1 + a2 ## array([11, 14, 17, 20, 23])

a3 = np.array([1,2,3]) #operands could not be broadcast together with shapes (5,) (3,)
# a1+a3                  # recycling of aaray would not happen like R lang

In [238]:
a1 = np.array([6,7,8,9,1,2,3,4,2,3,4,5])
len(a1)

a2 = a1.reshape(3,4)
a2

a3 = np.array([1,2,3,4])
a5 = a2 + a3  # all values of a3 will add in entire in a2
a5

array([[ 7,  9, 11, 13],
       [ 2,  4,  6,  8],
       [ 3,  5,  7,  9]])

In [246]:
a4 = np.array([2,1,3])
a4

a4 = a4.reshape(-1,1)
a4

a5 + a4
a5

array([[ 7,  9, 11, 13],
       [ 2,  4,  6,  8],
       [ 3,  5,  7,  9]])

In [255]:
a1 = np.array([6,7,8,9,1,2,3,4,2,3,4,5])
print(a1[4])
print(a1[[0,2,4,6]])

1
[6 8 1 3]


In [256]:
# Q1 where are the values are greater than 4    ----> index
# Q2 how many values are greater than 4         ----> count
# Q3 what are the  values which are greater than 4 --> other value

# input to the  np.where command is the condition to be checked.
# output of np.where command are the indicies where that condition found true.

In [264]:
var1 = np.where(a1 > 4) # it return the indexes where condition is true
print(var1)



print( type(var1) ) # returns tuple
print( len(var1) )
print( len(var1[0]) )

(array([ 0,  1,  2,  3, 11]),)
<class 'tuple'>
1
5
