<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/Stats/Day_1_stats_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd

In [45]:
x1 =[4,8,7,6,9]
type(x1)

str(x1)
type(x1)

a1 = np.array(x1)
type(a1)

numpy.ndarray

In [50]:
x2 = [6,9,1,3,2]

#Creating 2D array
a2 = np.array([x1,x2])
a2


[i for i in range(11)]

list(range(11))

a1 = np.arange(11)
a1

a2 = np.arange(8,11)
a2

a3 = np.arange(24,5,-2)
a3

a3 = np.arange(5,25,4)
a3

a3 = np.arange(2,20,2)
a3

a3 = np.arange(10,2,-2)
a3

array([10,  8,  6,  4])

In [74]:
np.linspace(10,20,2)

#this cmd givea array including the start and end this command give gap between them
# 3rd values can not be in decimal . bcz we are dividing the numbers in gaps

np.linspace(10,27,6)

np.linspace(10,27, 6, endpoint= False)
# endpoint will be excluded

array([10.        , 12.83333333, 15.66666667, 18.5       , 21.33333333,
       24.16666667])

In [75]:
a1 = np.array([4,8,6,5,9])
a1

np.append(a1,3)

a1 = np.append(a1,3)
a1

a2 = np.array([2,9,8])

a3 = np.concatenate((a1,a2))
a3

a1

array([4, 8, 6, 5, 9, 3])

In [ ]:
## remove, pop, del are cmds used to removing elemts from list.

In [80]:
a1 = np.array([3,6,5,7,8])
a2 = np.insert(a1,3,9)

a1
a2

np.delete(a2,2)

array([3, 6, 9, 7, 8])

In [95]:
a1 = np.array([3, 2, 6, 7, 8, 5, 4, 6])
a1

len(a1)

a2 = a1.reshape(4,2)
a2

# array([[3, 2],   after seeing the no. of square brackets give the count of dimensions of array
#        [6, 7],
#        [8, 5],
#        [4, 6]])


a3 = a1.reshape(2,4)
a3


a4 = a1.reshape(2,2,2)
a4

#==========================================================================

a1 = np.array([3, 2, 6, 7, 8, 5, 4, 6, 1])
a1

len(a1)

a2 = a1.reshape(3,3)
a2


array([[3, 2, 6],
       [7, 8, 5],
       [4, 6, 1]])